spring:
  application:
    name: pong


server:
  port: 8090


logging:
  level:
    root: INFO
    com.liuzhijun: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}.log  # log file path
    pattern: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"